<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="18" passed="9" failed="9" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-02T12:39:58 WET" name="Test Suite" finished-at="2025-01-02T12:47:14 WET" duration-ms="435785">
    <groups>
    </groups>
    <test started-at="2025-01-02T12:39:58 WET" name="Client Tests" finished-at="2025-01-02T12:47:14 WET" duration-ms="435785">
      <class name="TestCases.UserFAQTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:00 WET" name="setup" finished-at="2025-01-02T12:43:04 WET" duration-ms="3692" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC001_User_can_able_to_verify_the_category_to_each_FAQ()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:04 WET" name="TC001_User_can_able_to_verify_the_category_to_each_FAQ" finished-at="2025-01-02T12:43:10 WET" duration-ms="6077" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.UserFAQTest.TC001_User_can_able_to_verify_the_category_to_each_FAQ(UserFAQTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_User_can_able_to_verify_the_category_to_each_FAQ -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:10 WET" name="tearDown" finished-at="2025-01-02T12:43:11 WET" duration-ms="707" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:11 WET" name="setup" finished-at="2025-01-02T12:43:14 WET" duration-ms="3786" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC002_User_can_able_to_verify_the_reportIssue_and_BookMark_Button_in_FAQ()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:14 WET" name="TC002_User_can_able_to_verify_the_reportIssue_and_BookMark_Button_in_FAQ" finished-at="2025-01-02T12:43:42 WET" duration-ms="28107" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.UserFAQTest.TC002_User_can_able_to_verify_the_reportIssue_and_BookMark_Button_in_FAQ(UserFAQTest.java:121)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_User_can_able_to_verify_the_reportIssue_and_BookMark_Button_in_FAQ -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:42 WET" name="tearDown" finished-at="2025-01-02T12:43:43 WET" duration-ms="393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:43 WET" name="setup" finished-at="2025-01-02T12:43:46 WET" duration-ms="3098" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC003_User_can_able_to_verify_that_FAQ_reportIssue_can_able_to_send()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:46 WET" name="TC003_User_can_able_to_verify_that_FAQ_reportIssue_can_able_to_send" finished-at="2025-01-02T12:43:57 WET" duration-ms="11455" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.UserFAQTest.TC003_User_can_able_to_verify_that_FAQ_reportIssue_can_able_to_send(UserFAQTest.java:185)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003_User_can_able_to_verify_that_FAQ_reportIssue_can_able_to_send -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:57 WET" name="tearDown" finished-at="2025-01-02T12:43:58 WET" duration-ms="334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:43:58 WET" name="setup" finished-at="2025-01-02T12:44:01 WET" duration-ms="3108" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC004_User_can_able_to_verify_that_like_and_dislike_the_FAQ()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:44:01 WET" name="TC004_User_can_able_to_verify_that_like_and_dislike_the_FAQ" finished-at="2025-01-02T12:44:07 WET" duration-ms="6555" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.UserFAQTest.TC004_User_can_able_to_verify_that_like_and_dislike_the_FAQ(UserFAQTest.java:231)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC004_User_can_able_to_verify_that_like_and_dislike_the_FAQ -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.UserFAQTest@4b741d6d]" started-at="2025-01-02T12:44:07 WET" name="tearDown" finished-at="2025-01-02T12:44:08 WET" duration-ms="301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.UserFAQTest -->
      <class name="TestCases.AdminFAQTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:44:36 WET" name="setup" finished-at="2025-01-02T12:44:39 WET" duration-ms="2996" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC001_Admin_can_able_to_Create_the_New_Category()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:44:39 WET" name="TC001_Admin_can_able_to_Create_the_New_Category" finished-at="2025-01-02T12:44:55 WET" duration-ms="16145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_Admin_can_able_to_Create_the_New_Category -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:44:55 WET" name="tearDown" finished-at="2025-01-02T12:44:56 WET" duration-ms="466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:44:56 WET" name="setup" finished-at="2025-01-02T12:44:59 WET" duration-ms="2879" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC002_Admin_can_able_to_Create_the_Question_and_Answer_of_the_Category()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:44:59 WET" name="TC002_Admin_can_able_to_Create_the_Question_and_Answer_of_the_Category" finished-at="2025-01-02T12:45:24 WET" duration-ms="25431" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_Admin_can_able_to_Create_the_Question_and_Answer_of_the_Category -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:45:24 WET" name="tearDown" finished-at="2025-01-02T12:45:24 WET" duration-ms="403" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:45:24 WET" name="setup" finished-at="2025-01-02T12:45:27 WET" duration-ms="2681" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC003_Admin_can_able_to_Edit_and_Delete_the_existing_Category()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:45:27 WET" name="TC003_Admin_can_able_to_Edit_and_Delete_the_existing_Category" finished-at="2025-01-02T12:45:47 WET" duration-ms="19894" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003_Admin_can_able_to_Edit_and_Delete_the_existing_Category -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:45:47 WET" name="tearDown" finished-at="2025-01-02T12:45:47 WET" duration-ms="417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:45:47 WET" name="setup" finished-at="2025-01-02T12:45:50 WET" duration-ms="2912" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC004_Admin_can_able_to_Edit_and_Delete_the_Question_and_Answer_of_the_Category()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:45:50 WET" name="TC004_Admin_can_able_to_Edit_and_Delete_the_Question_and_Answer_of_the_Category" finished-at="2025-01-02T12:46:26 WET" duration-ms="35515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC004_Admin_can_able_to_Edit_and_Delete_the_Question_and_Answer_of_the_Category -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:46:26 WET" name="tearDown" finished-at="2025-01-02T12:46:26 WET" duration-ms="542" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:46:26 WET" name="setup" finished-at="2025-01-02T12:46:29 WET" duration-ms="3114" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC005_Admin_can_able_to_Verify_the_each_tab()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:46:29 WET" name="TC005_Admin_can_able_to_Verify_the_each_tab" finished-at="2025-01-02T12:46:35 WET" duration-ms="5045" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.AdminFAQTest.TC005_Admin_can_able_to_Verify_the_each_tab(AdminFAQTest.java:312)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC005_Admin_can_able_to_Verify_the_each_tab -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:46:35 WET" name="tearDown" finished-at="2025-01-02T12:46:35 WET" duration-ms="366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:46:35 WET" name="setup" finished-at="2025-01-02T12:46:38 WET" duration-ms="2696" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC006_Admin_can_able_to_Search_the_Category()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:46:38 WET" name="TC006_Admin_can_able_to_Search_the_Category" finished-at="2025-01-02T12:47:13 WET" duration-ms="35728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC006_Admin_can_able_to_Search_the_Category -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminFAQTest@8f2ef19]" started-at="2025-01-02T12:47:13 WET" name="tearDown" finished-at="2025-01-02T12:47:14 WET" duration-ms="408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.AdminFAQTest -->
      <class name="TestCases.UserReportIssueTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:08 WET" name="setup" finished-at="2025-01-02T12:44:10 WET" duration-ms="2797" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC001_User_can_able_to_send_Issue_report_with_user_details()[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:10 WET" name="TC001_User_can_able_to_send_Issue_report_with_user_details" finished-at="2025-01-02T12:44:17 WET" duration-ms="6555" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_User_can_able_to_send_Issue_report_with_user_details -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:17 WET" name="tearDown" finished-at="2025-01-02T12:44:17 WET" duration-ms="336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:17 WET" name="setup" finished-at="2025-01-02T12:44:20 WET" duration-ms="2789" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC002_User_can_able_to_send_Issue_report_Anonymously()[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:20 WET" name="TC002_User_can_able_to_send_Issue_report_Anonymously" finished-at="2025-01-02T12:44:27 WET" duration-ms="6766" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_User_can_able_to_send_Issue_report_Anonymously -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:27 WET" name="tearDown" finished-at="2025-01-02T12:44:27 WET" duration-ms="389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:27 WET" name="setup" finished-at="2025-01-02T12:44:30 WET" duration-ms="2822" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC003_User_cannot_able_to_send_Issue_report_without_type_of_Issue_and_Description()[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:30 WET" name="TC003_User_cannot_able_to_send_Issue_report_without_type_of_Issue_and_Description" finished-at="2025-01-02T12:44:36 WET" duration-ms="5556" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.UserReportIssueTest.TC003_User_cannot_able_to_send_Issue_report_without_type_of_Issue_and_Description(UserReportIssueTest.java:155)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003_User_cannot_able_to_send_Issue_report_without_type_of_Issue_and_Description -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.UserReportIssueTest@2eae8e6e]" started-at="2025-01-02T12:44:36 WET" name="tearDown" finished-at="2025-01-02T12:44:36 WET" duration-ms="377" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.UserReportIssueTest -->
      <class name="TestCases.AdminReportIssueTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:39:58 WET" name="setup" finished-at="2025-01-02T12:40:03 WET" duration-ms="5337" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC001_Admin_can_able_to_click_on_the_navigation_issue_report()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:40:03 WET" name="TC001_Admin_can_able_to_click_on_the_navigation_issue_report" finished-at="2025-01-02T12:40:09 WET" duration-ms="5472" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_Admin_can_able_to_click_on_the_navigation_issue_report -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:40:09 WET" name="tearDown" finished-at="2025-01-02T12:40:09 WET" duration-ms="384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:40:09 WET" name="setup" finished-at="2025-01-02T12:40:12 WET" duration-ms="2866" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC002_Admin_can_able_to_open_the_Reported_issue()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:40:12 WET" name="TC002_Admin_can_able_to_open_the_Reported_issue" finished-at="2025-01-02T12:40:28 WET" duration-ms="15504" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//h5[contains(@class, 'mx-name-text3')]"}
  (Session info: chrome=131.0.6778.205)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [bd7c1d241ed9b47f30ab91492bd7f118, findElement {using=xpath, value=//h5[contains(@class, 'mx-name-text3')]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.205, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\phyne\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64949}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64949/devtoo..., se:cdpVersion: 131.0.6778.205, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: bd7c1d241ed9b47f30ab91492bd7f118]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//h5[contains(@class, 'mx-name-text3')]"}
  (Session info: chrome=131.0.6778.205)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [bd7c1d241ed9b47f30ab91492bd7f118, findElement {using=xpath, value=//h5[contains(@class, 'mx-name-text3')]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.205, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\phyne\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64949}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64949/devtoo..., se:cdpVersion: 131.0.6778.205, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: bd7c1d241ed9b47f30ab91492bd7f118
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy14.getText(Unknown Source)
at TestCases.AdminReportIssueTest.TC002_Admin_can_able_to_open_the_Reported_issue(AdminReportIssueTest.java:87)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_Admin_can_able_to_open_the_Reported_issue -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:40:28 WET" name="tearDown" finished-at="2025-01-02T12:40:28 WET" duration-ms="398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:40:28 WET" name="setup" finished-at="2025-01-02T12:40:31 WET" duration-ms="2859" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC003_Admin_can_able_to_respond_the_reported_issue_into_Inprogress()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:40:31 WET" name="TC003_Admin_can_able_to_respond_the_reported_issue_into_Inprogress" finished-at="2025-01-02T12:41:38 WET" duration-ms="67541" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //h5[contains(@class, 'mx-name-text17')]' (tried for 50 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //h5[contains(@class, 'mx-name-text17')]' (tried for 50 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at TestCases.AdminReportIssueTest.TC003_Admin_can_able_to_respond_the_reported_issue_into_Inprogress(AdminReportIssueTest.java:137)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//h5[contains(@class, 'mx-name-text17')]"}
  (Session info: chrome=131.0.6778.205)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [ed0a41a736c3c6377e9b0c0ae2249c5d, findElement {using=xpath, value=//h5[contains(@class, 'mx-name-text17')]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.205, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\phyne\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64977}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64977/devtoo..., se:cdpVersion: 131.0.6778.205, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: ed0a41a736c3c6377e9b0c0ae2249c5d
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy14.isDisplayed(Unknown Source)
at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:304)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:290)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:287)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:203)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003_Admin_can_able_to_respond_the_reported_issue_into_Inprogress -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:41:38 WET" name="tearDown" finished-at="2025-01-02T12:41:39 WET" duration-ms="406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:41:39 WET" name="setup" finished-at="2025-01-02T12:41:42 WET" duration-ms="3021" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC004_Admin_can_able_to_respond_the_reported_issue_into_Resolved()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:41:42 WET" name="TC004_Admin_can_able_to_respond_the_reported_issue_into_Resolved" finished-at="2025-01-02T12:42:50 WET" duration-ms="67656" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //h5[contains(@class, 'mx-name-text17')]' (tried for 50 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //h5[contains(@class, 'mx-name-text17')]' (tried for 50 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at TestCases.AdminReportIssueTest.TC004_Admin_can_able_to_respond_the_reported_issue_into_Resolved(AdminReportIssueTest.java:178)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//h5[contains(@class, 'mx-name-text17')]"}
  (Session info: chrome=131.0.6778.205)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [63adf348296f8a627a6668607be89417, findElement {using=xpath, value=//h5[contains(@class, 'mx-name-text17')]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.205, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\phyne\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:65037}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:65037/devtoo..., se:cdpVersion: 131.0.6778.205, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 63adf348296f8a627a6668607be89417
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy14.isDisplayed(Unknown Source)
at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:304)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:290)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:287)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:203)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC004_Admin_can_able_to_respond_the_reported_issue_into_Resolved -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:42:50 WET" name="tearDown" finished-at="2025-01-02T12:42:50 WET" duration-ms="447" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:42:50 WET" name="setup" finished-at="2025-01-02T12:42:53 WET" duration-ms="3117" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[client]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC005_Admin_cannot_able_to_respond_the_reported_issue_without_comment()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:42:53 WET" name="TC005_Admin_cannot_able_to_respond_the_reported_issue_without_comment" finished-at="2025-01-02T12:43:00 WET" duration-ms="6626" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC005_Admin_cannot_able_to_respond_the_reported_issue_without_comment -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.AdminReportIssueTest@7b36aa0c]" started-at="2025-01-02T12:43:00 WET" name="tearDown" finished-at="2025-01-02T12:43:00 WET" duration-ms="301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.AdminReportIssueTest -->
    </test> <!-- Client Tests -->
  </suite> <!-- Test Suite -->
</testng-results>
