<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-P31RG0TB" failures="1" tests="6" name="TestCases.AdminFAQTest" time="157.638" errors="0" timestamp="2025-01-02T12:47:14 WET" skipped="0">
  <testcase classname="TestCases.AdminFAQTest" name="TC001_Admin_can_able_to_Create_the_New_Category" time="19.683"/>
  <system-out/>
  <testcase classname="TestCases.AdminFAQTest" name="TC002_Admin_can_able_to_Create_the_Question_and_Answer_of_the_Category" time="28.953"/>
  <system-out/>
  <testcase classname="TestCases.AdminFAQTest" name="TC004_Admin_can_able_to_Edit_and_Delete_the_Question_and_Answer_of_the_Category" time="38.562"/>
  <system-out/>
  <testcase classname="TestCases.AdminFAQTest" name="TC006_Admin_can_able_to_Search_the_Category" time="39.057"/>
  <system-out/>
  <testcase classname="TestCases.AdminFAQTest" name="TC003_Admin_can_able_to_Edit_and_Delete_the_existing_Category" time="23.176"/>
  <system-out/>
  <testcase classname="TestCases.AdminFAQTest" name="TC005_Admin_can_able_to_Verify_the_each_tab" time="8.207">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.AdminFAQTest.TC005_Admin_can_able_to_Verify_the_each_tab(AdminFAQTest.java:312)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC005_Admin_can_able_to_Verify_the_each_tab -->
  <system-out/>
</testsuite> <!-- TestCases.AdminFAQTest -->
